In [1]:
import torch

In [3]:
tensor_id = torch.tensor([1,2,3,4,5])

In [4]:
print(tensor_id)

tensor([1, 2, 3, 4, 5])


In [5]:
type(tensor_id)

torch.Tensor

In [14]:
tensor_a=torch.tensor([1,2,3,5])
tensor_b=torch.tensor([2,3,4,5])

In [15]:
result_addition = tensor_a + tensor_b
result_addition

tensor([ 3,  5,  7, 10])

In [16]:
result_subtraction = tensor_a-tensor_b
result_subtraction

tensor([-1, -1, -1,  0])

In [18]:
result_multiplication = tensor_a*tensor_b
result_multiplication

tensor([ 2,  6, 12, 25])

In [33]:
matrix_a = torch.tensor([[1,2],[3,4]])

In [34]:
matrix_b = torch.tensor([[2,3],[3,4]])
result_matrix = torch.mm(matrix_a, matrix_b)
result_matrix

tensor([[ 8, 11],
        [18, 25]])

In [29]:
original_tensor = torch.tensor([[1,2,3],[4,5,6]])
reshaped_tensor = original_tensor.view(6,1)
print(f"Original : {original_tensor}")
reshaped_tensor

Original : tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [37]:
tensor_c = torch.tensor([[1,2,3],[3,4,5]])
tensor_c[1][0]

tensor(3)

In [49]:
tensor_for_reduction = torch.tensor([[1,2,3],[4,5,6]])
torch.sum(tensor_for_reduction,dim=-1)

tensor([ 6, 15])

In [52]:
torch.cat((tensor_a,tensor_b),dim=-1)

tensor([1, 2, 3, 5, 2, 3, 4, 5])

In [56]:
a = torch.rand(2,6)

In [58]:
torch.sort(a)

torch.return_types.sort(
values=tensor([[0.1529, 0.1586, 0.3539, 0.5659, 0.6742, 0.7353],
        [0.0636, 0.5038, 0.6794, 0.7458, 0.7851, 0.7987]]),
indices=tensor([[4, 2, 0, 1, 3, 5],
        [3, 0, 4, 2, 5, 1]]))

In [60]:
tensor_for_grad = torch.tensor([2.0], requires_grad=True)

In [69]:
result = tensor_for_grad ** 2
result

tensor([4.], grad_fn=<PowBackward0>)

In [70]:
print(result.backward())

None


In [67]:
result

tensor([4.], grad_fn=<PowBackward0>)